# Generated by Django 3.2.6 on 2021-08-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('press', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('translator', models.CharField(max_length=255)),
                ('publication_year', models.DateField()),
                ('page_num', models.IntegerField()),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
